### ISSUE TITLE
fix: Google news provider doesn't work

### ISSUE THREAD

**Issue by ClementJosso** [ActualIA/app#159]
If you have only Google news in your settings as your sources, the call in the supabase function doesn't work, and the logs raise the following error : MessageError while fetching from "/google/news/:query/en": Error: Type html is not supported

**Comment by Thechi2000** [comment]
It seems the route for google new of RSS Hub is failing. The easiest solution is to use the original RSS feed (https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en).
